# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [19]:
# Create a 1-dimensional NumPy array using np.array()
one_dim_array = np.array([4, 5, 6])

# Create a 2-dimensional NumPy array using np.array()
two_dim_array = np.array([[4, 3, 2],
                          [9, 8, 7],
                          [0, 1, 2]])

# Create a 3-dimensional Numpy array using np.array()
three_dim_array = np.array([[[1, 2, 3],
                             [4, 5, 6],
                             [7, 8, 9]],
                            [[10, 11, 12],
                             [13, 14, 15],
                             [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [20]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
one_dim_array.ndim, one_dim_array.shape, one_dim_array.dtype

(1, (3,), dtype('int32'))

In [21]:
# Attributes of 2-dimensional array
two_dim_array.ndim, two_dim_array.shape, two_dim_array.dtype

(2, (3, 3), dtype('int32'))

In [22]:
# Attributes of 3-dimensional array
three_dim_array.ndim, three_dim_array.shape, three_dim_array.dtype

(3, (2, 3, 3), dtype('int32'))

In [25]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
dataFrame = pd.DataFrame(two_dim_array)
dataFrame

0  1  2
0  4  3  2
1  9  8  7
2  0  1  2

In [26]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [30]:
# Create an array within a range of 0 and 100 with step 3
range_Array = np.arange(0, 100, 3)
range_Array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [31]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, size = (7, 2))
random_array

array([[4, 8],
       [5, 0],
       [8, 4],
       [5, 5],
       [6, 0],
       [1, 5],
       [6, 5]])

In [34]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
float_np_array = np.random.random((3, 5))
float_np_array

array([[0.00463967, 0.05463451, 0.56016166, 0.78100555, 0.03204465],
       [0.68949437, 0.74908248, 0.87578798, 0.58132276, 0.62906421],
       [0.61851263, 0.80308673, 0.51363766, 0.38673332, 0.90427248]])

In [37]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_1 = np.random.randint(0, 10, size = (4, 6))
random_array_1

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

The Numbers aren't changing because of the random.seed() function

In [39]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_np_array = np.random.randint(1, 10, size = (3, 7))

# Find the unique numbers in the array you just created
np.unique(random_np_array)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# Find the 0'th index of the latest array you created
random_np_array[0]

array([7, 8, 3, 1, 4, 2, 8])

In [45]:
# Get the first 2 rows of latest array you created
random_np_array[:2]

array([[7, 8, 3, 1, 4, 2, 8],
       [4, 2, 6, 6, 4, 6, 2]])

In [56]:
# Get the first 2 values of the first 2 rows of the latest array
random_np_array[:2, :2]


array([[7, 8],
       [4, 2]])

In [62]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a1 = np.random.randint(0, 10, size = (3, 5))
a2 = np.random.randint(0, 10, size = (3, 5))
a1, a2

(array([[7, 0, 5, 7, 4],
        [3, 1, 5, 5, 0],
        [8, 5, 2, 3, 3]]),
 array([[2, 9, 2, 2, 3],
        [6, 3, 8, 0, 7],
        [6, 1, 7, 0, 8]]))

In [58]:
# Add the two arrays together
a1 + a2

array([[ 1, 11,  9, 11,  8],
       [12,  9, 14, 15, 16],
       [13,  8, 14,  8,  2]])

In [66]:
# Create another array of ones of shape (5, 3)
ones = np.ones((5, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
# Try add the array of ones and the other most recent array together
a1 + ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?
The Two rules for broadcasting are voilating here. This errror can be fixed by reshaping the the second array to (5, 3)

In [72]:
# Create another array of ones of shape (3, 5)
ones1 = np.ones((3, 5))

In [73]:
# Subtract the new array of ones from the other most recent array
ones - ones1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
# Multiply the ones array with the latest array
a3 = ones * a1
a3

array([[7., 0., 5., 7., 4.],
       [3., 1., 5., 5., 0.],
       [8., 5., 2., 3., 3.]])

In [77]:
# Take the latest array to the power of 2 using '**'
a3 ** 2

array([[49.,  0., 25., 49., 16.],
       [ 9.,  1., 25., 25.,  0.],
       [64., 25.,  4.,  9.,  9.]])

In [78]:
# Do the same thing with np.square()
np.square(a3)

array([[49.,  0., 25., 49., 16.],
       [ 9.,  1., 25., 25.,  0.],
       [64., 25.,  4.,  9.,  9.]])

In [80]:
# Find the mean of the latest array using np.mean()
np.mean(a3)

3.8666666666666667

In [81]:
# Find the maximum of the latest array using np.max()
np.max(a3)

8.0

In [82]:
# Find the minimum of the latest array using np.min()
np.min(a3)

0.0

In [83]:
# Find the standard deviation of the latest array
np.std(a3)

2.390722810272148

In [84]:
# Find the variance of the latest array
np.var(a3)

5.715555555555556

In [85]:
# Reshape the latest array to (3, 5, 1)
a3.reshape(3, 5, 1)

array([[[7.],
        [0.],
        [5.],
        [7.],
        [4.]],

       [[3.],
        [1.],
        [5.],
        [5.],
        [0.]],

       [[8.],
        [5.],
        [2.],
        [3.],
        [3.]]])

In [86]:
# Transpose the latest array
a3.T

array([[7., 3., 8.],
       [0., 1., 5.],
       [5., 5., 2.],
       [7., 5., 3.],
       [4., 0., 3.]])

What does the transpose do?

Covert rows into columns

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [88]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a4 = np.random.randint(0, 10, size = (4, 7))
a5 = np.random.randint(0, 10, size = (4, 7))
a4, a5

(array([[8, 1, 6, 9, 2, 6, 9],
        [8, 3, 0, 1, 0, 4, 4],
        [6, 8, 8, 2, 2, 2, 3],
        [7, 5, 7, 0, 7, 3, 0]]),
 array([[7, 3, 5, 7, 3, 2, 8],
        [2, 8, 1, 1, 1, 5, 2],
        [8, 3, 0, 3, 0, 4, 3],
        [7, 7, 6, 2, 0, 0, 2]]))

In [89]:
# Compare the two arrays with '>'
a4 > a5

array([[ True, False,  True,  True, False,  True,  True],
       [ True, False, False, False, False, False,  True],
       [False,  True,  True, False,  True, False, False],
       [False, False,  True, False,  True,  True, False]])

What happens when you compare the arrays with `>`?

In [90]:
# Compare the two arrays with '>='
a4 >= a5

array([[ True, False,  True,  True, False,  True,  True],
       [ True, False, False,  True, False, False,  True],
       [False,  True,  True, False,  True, False,  True],
       [ True, False,  True, False,  True,  True, False]])

In [91]:
# Find which elements of the first array are greater than 7
a4 > 7

array([[ True, False, False,  True, False, False,  True],
       [ True, False, False, False, False, False, False],
       [False,  True,  True, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [92]:
# Which parts of each array are equal? (try using '==')
a4 == a5

array([[False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False],
       [False, False, False, False, False, False,  True],
       [ True, False, False, False, False, False, False]])

In [93]:
# Sort one of the arrays you just created in ascending order
np.sort(a4)

array([[1, 2, 6, 6, 8, 9, 9],
       [0, 0, 1, 3, 4, 4, 8],
       [2, 2, 2, 3, 6, 8, 8],
       [0, 0, 3, 5, 7, 7, 7]])

In [94]:
# Sort the indexes of one of the arrays you just created
np.argsort(a4)

array([[1, 4, 2, 5, 0, 3, 6],
       [2, 4, 3, 1, 5, 6, 0],
       [3, 4, 5, 6, 0, 1, 2],
       [3, 6, 5, 1, 0, 2, 4]], dtype=int64)

In [96]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a5)

6

In [97]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a5)

16

In [99]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(a5, axis=1)

array([6, 1, 0, 0], dtype=int64)

In [100]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(a5, axis=0)

array([1, 0, 2, 1, 2, 3, 1], dtype=int64)

In [101]:
# Create an array of normally distributed random numbers
np.random.randn(3, 5)


array([[-1.31857016,  0.72038724,  0.31589091,  0.05928128,  0.91051222],
       [-0.02972536, -1.93637621, -0.84735753,  1.36443345,  1.1720289 ],
       [-0.37311919,  0.50359706,  2.78393805, -0.0311868 , -0.01158332]])

In [102]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)


array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.